version: '3.8'

services:
    mongodb:
        image: mongo:7.0
        container_name: www_mongo_service
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: ecommerce
        volumes:
            - mongo_data:/data/db
        networks:
            - ecommerce_net
        restart: unless-stopped
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        container_name: www_back_ecommerce
        ports:
            - '${PORT:-3000}:3000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://root:secret@mongodb:27017/ecommerce?authSource=admin
            - PORT=3000
            - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
            - DEFAULT_PAGE_SIZE=${DEFAULT_PAGE_SIZE:-10}
            - MAX_PAGE_SIZE=${MAX_PAGE_SIZE:-100}
            - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5MB}
            - UPLOAD_PATH=${UPLOAD_PATH:-./uploads}
        volumes:
            - uploads_data:/app/uploads
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - ecommerce_net
        restart: unless-stopped
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3000/health',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s

networks:
    ecommerce_net:
        driver: bridge

volumes:
    mongo_data:
    uploads_data:
